[package]
name = "credits"
version = "0.1.0"
authors = ["Asbjørn Clemmensen <ac@siteimprove.com>"]

[dependencies]
uuid = { version = "0.7", features = ["serde", "v4"] }
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
stopwatch = "0.0.7"